# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7152097300c0868fb4a4eeb96f5bcbcddb14878e832c56df2a13359881a559e73ad3f23ad43a4bb3308cea5664a3f01d2950a32d4649dccf89bde82dcd54258f

test:
  secret_key_base: a730cddf35693e73a7b8d0c63c1ea72d05502d77d261919ab3f9dc952901b9119761590d98b7ff5979d4790e012651cf4d82967e56721f5cb7603092490b5585

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
